export const ALL_NOTICE_REQUEST="ALL_NOTICE_REQUEST";
export const ALL_NOTICE_SUCCESS="ALL_NOTICE_SUCCESS";
export const ALL_NOTICE_FAILD="ALL_NOTICE_FALLD";

export const GET_TEACHERS_REQUEST="GET_TEACHERS_REQUEST";
export const GET_TEACHERS_SUCCESS="GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_FAILD="GET_TEACHERS_FALLD";

export const CLEAR_ERRORS="CEAR_ERRORS";