export const EMAIL_SEND_REQUEST="EMAIL_SEND_REQUEST";
export const EMAIL_SEND_SUCCESS="EMAIL_SEND_SUCCESS";
export const EMAIL_SEND_FAILED="EMAIL_SEND_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
